language: php
php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist --no-autoloader

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src

notifications:
  email: false
