language: php
php:
  - 7.1
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src/

notifications:
  email: false
